### ISSUE TITLE
Spanish Soundcloud/Dropbox links swapped

### ISSUE THREAD

**Issue by tetelestia** [Kyubyong/css10#1]
Very small issue, but the links to the models and samples are swapped in in readme for Spanish.

**Comment by puentev** [comment]
And only TACOTRON model is provided. DCSS is missing.

**Comment by Kyubyong** [comment]
@tetelestia Thanks! I corrected
@puentev Would you check again? To me there seems no problem.

**Comment by puentev** [comment]
Works with TACOTRON but the model of DCTTS don't: both links goes to the same model (i.e, DCTTS won't work)

Besides this, I needed to change   EOS_char = '␃' by   EOS_char = '\n' in hyperparams.py

The TACOTRON model is just outstanding. The quality of the voice is amazing. With AVXV2 processor is really fast. I still can't  believe how a 109MB produces such quality :)

Thanks for such a great job.

**Comment by sysuzyx** [comment]
Hi~the links to audio sample are invalid

**Comment by Martin-Laclaustra** [comment]
@Kyubyong 
Thank you for the fantastic work and the generosity of sharing it here.
Please, revise the link of the DCTTS Spanish model. As stated above, both (DCTTS and Tacotron) links in the README.MD point to one same file, the Tacotron Spanish model.

**Comment by Kyubyong** [comment]
Oh I'm very sorry. Would you check again?

**Comment by Martin-Laclaustra** [comment]
Great! Thank you! That was fast!
I confirm that the model is available and working.
I think you can close this issue.
